# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Admin Publish Workflow

on:
  push:
    tags:
      - 'admin-v*' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./HanimeliApp.Admin.Api/HanimeliApp.Admin.Api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./HanimeliApp.Admin.Api/HanimeliApp.Admin.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/adminapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: admin-app
          path: ${{env.DOTNET_ROOT}}/adminapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: admin-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_869BE3AF45DA46489AC1DA8AA6DD60AF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_49629E0DE2DD4B60B59DAEC5B7879CA3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8066D3F5DAA74FE3B61D0114D33C96D2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hanimeli-admin-api'
          slot-name: 'Production'
          package: .
          