# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Mobile Publish Workflow

on:
  push:
    tags:
      - 'operation-v*' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./HanimeliApp.Operation.Api/HanimeliApp.Operation.Api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./HanimeliApp.Operation.Api/HanimeliApp.Operation.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/operationapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: operation-app
          path: ${{env.DOTNET_ROOT}}/operationapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: operation-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hanimeli-operation-api'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E141E41E993E4D5FBC872CBF0E0C8661 }}